// <auto-generated />
using Bourque.EMAILQueue.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bourque.EMAILQueue.EntityFramework.Migrations
{
    [DbContext(typeof(EmailQueueDbContext))]
    partial class EmailQueueDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Bourque.EMAILQueue.Data.Models.DbModels.EmailAttachement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueueRecordId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QueueRecordId");

                    b.ToTable("EmailAttachements");
                });

            modelBuilder.Entity("Bourque.EMAILQueue.Data.Models.DbModels.EmailQueueRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FromEmailEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FromEmailEmail");

                    b.ToTable("EmailQueueRecords");
                });

            modelBuilder.Entity("Bourque.EMAILQueue.Data.Models.DbModels.EmailServer", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SmtpServerAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SmtpServerUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Email");

                    b.ToTable("EmailServers");
                });

            modelBuilder.Entity("Bourque.EMAILQueue.Data.Models.DbModels.EmailAttachement", b =>
                {
                    b.HasOne("Bourque.EMAILQueue.Data.Models.DbModels.EmailQueueRecord", "QueueRecord")
                        .WithMany("Attachements")
                        .HasForeignKey("QueueRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QueueRecord");
                });

            modelBuilder.Entity("Bourque.EMAILQueue.Data.Models.DbModels.EmailQueueRecord", b =>
                {
                    b.HasOne("Bourque.EMAILQueue.Data.Models.DbModels.EmailServer", "FromEmail")
                        .WithMany()
                        .HasForeignKey("FromEmailEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromEmail");
                });

            modelBuilder.Entity("Bourque.EMAILQueue.Data.Models.DbModels.EmailQueueRecord", b =>
                {
                    b.Navigation("Attachements");
                });
#pragma warning restore 612, 618
        }
    }
}
